@url= https://booking-api-1-edu7.onrender.com

POST {{url}}/api/bookings
Content-type:application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "phone_number": "1234567890",
  "check_in_date": "2024-10-20",
  "checkout_date": "2024-10-25",
 
}


